version: '2'

services:
  web:
    build: .
    command: npm run start
    volumes:
      - .:/usr/src/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - api
    environment:
      DATABASE_URL: mongo
      API_URL: api
  api:
    build:
      context: .
      dockerfile: Dockerfile-node
    command: npm run server
    volumes:
      - .:/usr/src/app
      - /usr/app/node_modules
    ports:
      - "9000:9000"
    environment:
      DATABASE_URL: mongo
  mongo:
    image: 'bitnami/mongodb:3.6'
    labels:
      kompose.service.type: nodeport
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami'
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
volumes:
  mongodb_data:
    driver: local
