version: '2'

services:
  app:
    container_name: fitdash_app
    build:
      context: ./app
    volumes:
      - ./app:/app
      - /app/node_modules/
    ports:
      - "3001:3001"
  #   - graph
  # TODO
  # graph:
  #   build: .
  #   command: npm run graph
  #   volumes:
  #     - .:/usr/src/graph
  #     - /usr/app/node_modules
  #   ports:
  #     - "3002:3002"
  #   depends_on:
  #     - mongo
  #   environment:
  #     DATABASE_URL: mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - './mongo-db/mongodb_data:/data/db'
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
volumes:
  mongodb_data:
    driver: local
