name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
      - name: Install Dependencies
        working-directory: ./fitdash-sync
        run: yarn
      - name: Run linting
        working-directory: ./fitdash-sync
        run: yarn run lint
      - name: Run unit tests
        working-directory: ./fitdash-sync
        env:
          CI: true
        run: yarn run test

