name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        working-directory: ./fitdash-sync
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/setup-node@v2
      - name: Install Dependencies
        working-directory: ./fitdash-sync
        run: yarn
      - name: Run linting
        working-directory: ./fitdash-sync
        run: yarn run lint
      - name: Run unit tests
        working-directory: ./fitdash-sync
        env:
          CI: true
        run: yarn run test

